Sprint 1
encoreee/middle.messenger.praktikum.yandex pull request #3
Opened 2023-02-09 12:18 UTC by encoreee

2023-02-09 19:17 UTC, podlovchenko requested changes
Привет, в целом все хорошо, но необходимо задеплоить приложение на нетлифай и указать корректную ссылку в ридми

2023-02-09 19:17 UTC, podlovchenko commented on app.js
> +const PORT = 3000;
Часто требуется возможность получить порт снаружи скрипта, не изменяя код, это можно сделать через переменное окружение:
process.env.PORT || PORT;
https://nodejs.org/dist/latest-v8.x/docs/api/process.html

2023-02-09 19:17 UTC, podlovchenko commented on package.json
> +    "postcss-modules": "^4.3.0"
В devDependencies указывается то, что необходимо для сборки и разработки приложения, в dependencies то, что необходимо непосредственно для работу приложения (express)

2023-02-09 19:17 UTC, podlovchenko commented on package.json
> +    "@anikin/parcel-transformer-handlebars": "^1.0.9",
Лучше задавать фиксированные версии зависимостям. Если однажды решишь, удалить package-lock.json файл и попытаться повторно установить зависимости с помощью команды npm install, npm установит последние версии зависимостей, что может привести к ошибкам

2023-02-09 19:17 UTC, podlovchenko commented on package.json
> +    "start": "parcel build src/index.hbs --no-cache && node app.js",
Можно переиспользовать
```suggestion
    "start": "npm run build && node app.js",
```

2023-02-09 19:17 UTC, podlovchenko commented on src/styles/changeDataPage.css
> +  border-color: #bdbdbd;
Цвета лучше указывать через css переменные, так будет понятнее, что это за цвет при просмотре кода и проще редактировать цвета по всему проекту
https://developer.mozilla.org/ru/docs/Web/CSS/Using_CSS_custom_properties, придерживаться одной цветовой палитры

2023-02-10 20:48 UTC, encoreee commented on README.md
> +https://roaring-buttercream-a4193f.netlify.app
> 

Я подумал что workflow такой: sprint_1 > main > deploy > netlufy . Вот и не залил осознанно

2023-02-10 20:57 UTC, encoreee commented on package.json
> +    "postcss-modules": "^4.3.0"
ok

2023-02-10 20:58 UTC, encoreee commented on package.json
> +    "@anikin/parcel-transformer-handlebars": "^1.0.9",
ok

2023-02-10 20:59 UTC, encoreee commented on package.json
> +    "start": "parcel build src/index.hbs --no-cache && node app.js",
ok

2023-02-10 21:12 UTC, encoreee commented on .parcelrc
> +}
ok

2023-02-10 21:28 UTC, encoreee commented on app.js
> +const PORT = 3000;
ok

2023-02-11 14:39 UTC, encoreee commented on README.md
> +https://roaring-buttercream-a4193f.netlify.app
ok

2023-02-11 14:39 UTC, encoreee commented on src/styles/changeDataPage.css
> +  border-color: #bdbdbd;
ok

2023-02-11 14:46 UTC, encoreee commented
Привет,
Вроде бы не нужно открывать нового Pull request, что бы были видны изменения и коммиты. В общем прилагаю тогда ту же ссылку на PR.

2023-02-12 10:53 UTC, podlovchenko commented
Привет, спасибо за правки, работу принимаю)

2023-02-12 12:54 UTC, merged